// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/container_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerManager_Run_FullMethodName                = "/container_manager.ContainerManager/Run"
	ContainerManager_ListContainers_FullMethodName     = "/container_manager.ContainerManager/ListContainers"
	ContainerManager_GetContainerStatus_FullMethodName = "/container_manager.ContainerManager/GetContainerStatus"
	ContainerManager_Health_FullMethodName             = "/container_manager.ContainerManager/Health"
	ContainerManager_GetNodeResources_FullMethodName   = "/container_manager.ContainerManager/GetNodeResources"
	ContainerManager_GetAvailableImages_FullMethodName = "/container_manager.ContainerManager/GetAvailableImages"
)

// ContainerManagerClient is the client API for ContainerManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Container Manager Service
// Manages isolation-runner subprocesses for container lifecycle
type ContainerManagerClient interface {
	// Unified bidirectional stream for container lifecycle
	// First message MUST be RunRequest with create field set
	// Server sends stdout/stderr/messages/exit events
	// Client can send stdin
	// Client MUST send heartbeat every 30 seconds or container will be terminated
	// Connection close/interrupt automatically terminates container
	Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunRequest, RunResponse], error)
	// List all containers (running and recent)
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	// Get status of a specific container
	GetContainerStatus(ctx context.Context, in *GetContainerStatusRequest, opts ...grpc.CallOption) (*GetContainerStatusResponse, error)
	// Health check
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Get node resources (CPU, memory, disk)
	GetNodeResources(ctx context.Context, in *GetNodeResourcesRequest, opts ...grpc.CallOption) (*GetNodeResourcesResponse, error)
	// Get available Docker images on this node
	GetAvailableImages(ctx context.Context, in *GetAvailableImagesRequest, opts ...grpc.CallOption) (*GetAvailableImagesResponse, error)
}

type containerManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerManagerClient(cc grpc.ClientConnInterface) ContainerManagerClient {
	return &containerManagerClient{cc}
}

func (c *containerManagerClient) Run(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RunRequest, RunResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerManager_ServiceDesc.Streams[0], ContainerManager_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunRequest, RunResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerManager_RunClient = grpc.BidiStreamingClient[RunRequest, RunResponse]

func (c *containerManagerClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, ContainerManager_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagerClient) GetContainerStatus(ctx context.Context, in *GetContainerStatusRequest, opts ...grpc.CallOption) (*GetContainerStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerStatusResponse)
	err := c.cc.Invoke(ctx, ContainerManager_GetContainerStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagerClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ContainerManager_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagerClient) GetNodeResources(ctx context.Context, in *GetNodeResourcesRequest, opts ...grpc.CallOption) (*GetNodeResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResourcesResponse)
	err := c.cc.Invoke(ctx, ContainerManager_GetNodeResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagerClient) GetAvailableImages(ctx context.Context, in *GetAvailableImagesRequest, opts ...grpc.CallOption) (*GetAvailableImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableImagesResponse)
	err := c.cc.Invoke(ctx, ContainerManager_GetAvailableImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerManagerServer is the server API for ContainerManager service.
// All implementations must embed UnimplementedContainerManagerServer
// for forward compatibility.
//
// Container Manager Service
// Manages isolation-runner subprocesses for container lifecycle
type ContainerManagerServer interface {
	// Unified bidirectional stream for container lifecycle
	// First message MUST be RunRequest with create field set
	// Server sends stdout/stderr/messages/exit events
	// Client can send stdin
	// Client MUST send heartbeat every 30 seconds or container will be terminated
	// Connection close/interrupt automatically terminates container
	Run(grpc.BidiStreamingServer[RunRequest, RunResponse]) error
	// List all containers (running and recent)
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	// Get status of a specific container
	GetContainerStatus(context.Context, *GetContainerStatusRequest) (*GetContainerStatusResponse, error)
	// Health check
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Get node resources (CPU, memory, disk)
	GetNodeResources(context.Context, *GetNodeResourcesRequest) (*GetNodeResourcesResponse, error)
	// Get available Docker images on this node
	GetAvailableImages(context.Context, *GetAvailableImagesRequest) (*GetAvailableImagesResponse, error)
	mustEmbedUnimplementedContainerManagerServer()
}

// UnimplementedContainerManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerManagerServer struct{}

func (UnimplementedContainerManagerServer) Run(grpc.BidiStreamingServer[RunRequest, RunResponse]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedContainerManagerServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedContainerManagerServer) GetContainerStatus(context.Context, *GetContainerStatusRequest) (*GetContainerStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainerStatus not implemented")
}
func (UnimplementedContainerManagerServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedContainerManagerServer) GetNodeResources(context.Context, *GetNodeResourcesRequest) (*GetNodeResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeResources not implemented")
}
func (UnimplementedContainerManagerServer) GetAvailableImages(context.Context, *GetAvailableImagesRequest) (*GetAvailableImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableImages not implemented")
}
func (UnimplementedContainerManagerServer) mustEmbedUnimplementedContainerManagerServer() {}
func (UnimplementedContainerManagerServer) testEmbeddedByValue()                          {}

// UnsafeContainerManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerManagerServer will
// result in compilation errors.
type UnsafeContainerManagerServer interface {
	mustEmbedUnimplementedContainerManagerServer()
}

func RegisterContainerManagerServer(s grpc.ServiceRegistrar, srv ContainerManagerServer) {
	// If the following call panics, it indicates UnimplementedContainerManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerManager_ServiceDesc, srv)
}

func _ContainerManager_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ContainerManagerServer).Run(&grpc.GenericServerStream[RunRequest, RunResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerManager_RunServer = grpc.BidiStreamingServer[RunRequest, RunResponse]

func _ContainerManager_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerManager_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManager_GetContainerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).GetContainerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerManager_GetContainerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).GetContainerStatus(ctx, req.(*GetContainerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManager_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerManager_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManager_GetNodeResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).GetNodeResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerManager_GetNodeResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).GetNodeResources(ctx, req.(*GetNodeResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManager_GetAvailableImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagerServer).GetAvailableImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerManager_GetAvailableImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagerServer).GetAvailableImages(ctx, req.(*GetAvailableImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerManager_ServiceDesc is the grpc.ServiceDesc for ContainerManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "container_manager.ContainerManager",
	HandlerType: (*ContainerManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContainers",
			Handler:    _ContainerManager_ListContainers_Handler,
		},
		{
			MethodName: "GetContainerStatus",
			Handler:    _ContainerManager_GetContainerStatus_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ContainerManager_Health_Handler,
		},
		{
			MethodName: "GetNodeResources",
			Handler:    _ContainerManager_GetNodeResources_Handler,
		},
		{
			MethodName: "GetAvailableImages",
			Handler:    _ContainerManager_GetAvailableImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _ContainerManager_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/container_manager.proto",
}
