// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/container_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerState int32

const (
	ContainerState_CREATED    ContainerState = 0
	ContainerState_RUNNING    ContainerState = 1
	ContainerState_EXITED     ContainerState = 2
	ContainerState_FAILED     ContainerState = 3
	ContainerState_TERMINATED ContainerState = 4
)

// Enum value maps for ContainerState.
var (
	ContainerState_name = map[int32]string{
		0: "CREATED",
		1: "RUNNING",
		2: "EXITED",
		3: "FAILED",
		4: "TERMINATED",
	}
	ContainerState_value = map[string]int32{
		"CREATED":    0,
		"RUNNING":    1,
		"EXITED":     2,
		"FAILED":     3,
		"TERMINATED": 4,
	}
)

func (x ContainerState) Enum() *ContainerState {
	p := new(ContainerState)
	*p = x
	return p
}

func (x ContainerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_container_manager_proto_enumTypes[0].Descriptor()
}

func (ContainerState) Type() protoreflect.EnumType {
	return &file_proto_container_manager_proto_enumTypes[0]
}

func (x ContainerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerState.Descriptor instead.
func (ContainerState) EnumDescriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{0}
}

type RunRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*RunRequest_Create
	//	*RunRequest_Stdin
	//	*RunRequest_CloseStdin
	//	*RunRequest_Terminate
	//	*RunRequest_Heartbeat
	Request       isRunRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetRequest() isRunRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RunRequest) GetCreate() *CreateContainer {
	if x != nil {
		if x, ok := x.Request.(*RunRequest_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *RunRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Request.(*RunRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *RunRequest) GetCloseStdin() bool {
	if x != nil {
		if x, ok := x.Request.(*RunRequest_CloseStdin); ok {
			return x.CloseStdin
		}
	}
	return false
}

func (x *RunRequest) GetTerminate() *TerminateContainer {
	if x != nil {
		if x, ok := x.Request.(*RunRequest_Terminate); ok {
			return x.Terminate
		}
	}
	return nil
}

func (x *RunRequest) GetHeartbeat() bool {
	if x != nil {
		if x, ok := x.Request.(*RunRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return false
}

type isRunRequest_Request interface {
	isRunRequest_Request()
}

type RunRequest_Create struct {
	// MUST be sent as first message - creates and starts container
	Create *CreateContainer `protobuf:"bytes,1,opt,name=create,proto3,oneof"`
}

type RunRequest_Stdin struct {
	// Send stdin data to container
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type RunRequest_CloseStdin struct {
	// Close stdin stream
	CloseStdin bool `protobuf:"varint,3,opt,name=close_stdin,json=closeStdin,proto3,oneof"`
}

type RunRequest_Terminate struct {
	// Terminate container (optional - connection close also terminates)
	Terminate *TerminateContainer `protobuf:"bytes,4,opt,name=terminate,proto3,oneof"`
}

type RunRequest_Heartbeat struct {
	// Heartbeat - MUST be sent at least every 30 seconds or container will be terminated
	Heartbeat bool `protobuf:"varint,5,opt,name=heartbeat,proto3,oneof"`
}

func (*RunRequest_Create) isRunRequest_Request() {}

func (*RunRequest_Stdin) isRunRequest_Request() {}

func (*RunRequest_CloseStdin) isRunRequest_Request() {}

func (*RunRequest_Terminate) isRunRequest_Request() {}

func (*RunRequest_Heartbeat) isRunRequest_Request() {}

type CreateContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique ID for this container (if not provided, one will be generated)
	ContainerId *string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3,oneof" json:"container_id,omitempty"`
	// Container configuration
	Config        *ContainerConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainer) Reset() {
	*x = CreateContainer{}
	mi := &file_proto_container_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainer) ProtoMessage() {}

func (x *CreateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainer.ProtoReflect.Descriptor instead.
func (*CreateContainer) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContainer) GetContainerId() string {
	if x != nil && x.ContainerId != nil {
		return *x.ContainerId
	}
	return ""
}

func (x *CreateContainer) GetConfig() *ContainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type TerminateContainer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Force kill (SIGKILL) instead of graceful termination (SIGTERM)
	Force bool `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	// Timeout for graceful termination before force kill (seconds)
	TimeoutSecs   uint32 `protobuf:"varint,2,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateContainer) Reset() {
	*x = TerminateContainer{}
	mi := &file_proto_container_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateContainer) ProtoMessage() {}

func (x *TerminateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateContainer.ProtoReflect.Descriptor instead.
func (*TerminateContainer) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateContainer) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TerminateContainer) GetTimeoutSecs() uint32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type RunResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container ID for this stream
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*RunResponse_Created
	//	*RunResponse_Stdout
	//	*RunResponse_Stderr
	//	*RunResponse_Exit
	//	*RunResponse_Error
	//	*RunResponse_Message
	Event         isRunResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{3}
}

func (x *RunResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RunResponse) GetEvent() isRunResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RunResponse) GetCreated() *ContainerCreated {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Created); ok {
			return x.Created
		}
	}
	return nil
}

func (x *RunResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *RunResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *RunResponse) GetExit() *ContainerExit {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *RunResponse) GetError() string {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *RunResponse) GetMessage() string {
	if x != nil {
		if x, ok := x.Event.(*RunResponse_Message); ok {
			return x.Message
		}
	}
	return ""
}

type isRunResponse_Event interface {
	isRunResponse_Event()
}

type RunResponse_Created struct {
	// Container was created successfully
	Created *ContainerCreated `protobuf:"bytes,2,opt,name=created,proto3,oneof"`
}

type RunResponse_Stdout struct {
	// Stdout data from container
	Stdout []byte `protobuf:"bytes,3,opt,name=stdout,proto3,oneof"`
}

type RunResponse_Stderr struct {
	// Stderr data from container
	Stderr []byte `protobuf:"bytes,4,opt,name=stderr,proto3,oneof"`
}

type RunResponse_Exit struct {
	// Container exited
	Exit *ContainerExit `protobuf:"bytes,5,opt,name=exit,proto3,oneof"`
}

type RunResponse_Error struct {
	// Error occurred
	Error string `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type RunResponse_Message struct {
	// Raw JSON message from isolation-runner (info, debug, warning, etc.)
	Message string `protobuf:"bytes,7,opt,name=message,proto3,oneof"`
}

func (*RunResponse_Created) isRunResponse_Event() {}

func (*RunResponse_Stdout) isRunResponse_Event() {}

func (*RunResponse_Stderr) isRunResponse_Event() {}

func (*RunResponse_Exit) isRunResponse_Event() {}

func (*RunResponse_Error) isRunResponse_Event() {}

func (*RunResponse_Message) isRunResponse_Event() {}

type ContainerCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	State         ContainerState         `protobuf:"varint,2,opt,name=state,proto3,enum=container_manager.ContainerState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerCreated) Reset() {
	*x = ContainerCreated{}
	mi := &file_proto_container_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreated) ProtoMessage() {}

func (x *ContainerCreated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreated.ProtoReflect.Descriptor instead.
func (*ContainerCreated) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerCreated) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerCreated) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CREATED
}

type ContainerExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerExit) Reset() {
	*x = ContainerExit{}
	mi := &file_proto_container_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerExit) ProtoMessage() {}

func (x *ContainerExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerExit.ProtoReflect.Descriptor instead.
func (*ContainerExit) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerExit) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type ContainerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Docker image specification with optional authentication
	ImageSpec *ImageSpec `protobuf:"bytes,1,opt,name=image_spec,json=imageSpec,proto3" json:"image_spec,omitempty"`
	// Command to execute in container (overrides image's default ENTRYPOINT)
	// If not specified, uses the image's default ENTRYPOINT
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Working directory
	Workdir *string `protobuf:"bytes,3,opt,name=workdir,proto3,oneof" json:"workdir,omitempty"`
	// Environment variables
	Env map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource limits
	Resources *ResourceLimits `protobuf:"bytes,5,opt,name=resources,proto3,oneof" json:"resources,omitempty"`
	// Network configuration
	Network *NetworkConfig `protobuf:"bytes,6,opt,name=network,proto3,oneof" json:"network,omitempty"`
	// Timeout in seconds (0 = no timeout)
	TimeoutSecs *uint32 `protobuf:"varint,7,opt,name=timeout_secs,json=timeoutSecs,proto3,oneof" json:"timeout_secs,omitempty"`
	// Whether to cleanup container after exit
	Cleanup *bool `protobuf:"varint,8,opt,name=cleanup,proto3,oneof" json:"cleanup,omitempty"`
	// Arguments to pass to the command (overrides image's default CMD)
	// If command is not specified, these are passed to the image's default ENTRYPOINT
	// If command is specified, these are appended as arguments to that command
	Args          []string `protobuf:"bytes,9,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerConfig) Reset() {
	*x = ContainerConfig{}
	mi := &file_proto_container_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerConfig) ProtoMessage() {}

func (x *ContainerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerConfig.ProtoReflect.Descriptor instead.
func (*ContainerConfig) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerConfig) GetImageSpec() *ImageSpec {
	if x != nil {
		return x.ImageSpec
	}
	return nil
}

func (x *ContainerConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerConfig) GetWorkdir() string {
	if x != nil && x.Workdir != nil {
		return *x.Workdir
	}
	return ""
}

func (x *ContainerConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerConfig) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ContainerConfig) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *ContainerConfig) GetTimeoutSecs() uint32 {
	if x != nil && x.TimeoutSecs != nil {
		return *x.TimeoutSecs
	}
	return 0
}

func (x *ContainerConfig) GetCleanup() bool {
	if x != nil && x.Cleanup != nil {
		return *x.Cleanup
	}
	return false
}

func (x *ContainerConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Image specification with registry and authentication
type ImageSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registry hostname (defaults to "registry-1.docker.io" if not provided)
	// Examples: "gcr.io", "ghcr.io", "my-registry.local:5000"
	Registry *string `protobuf:"bytes,1,opt,name=registry,proto3,oneof" json:"registry,omitempty"`
	// Image name with tag or digest (without registry prefix)
	// Examples: "library/nginx:latest", "myorg/app@sha256:abc123..."
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Optional authentication credentials
	//
	// Types that are valid to be assigned to Auth:
	//
	//	*ImageSpec_BasicAuth
	Auth          isImageSpec_Auth `protobuf_oneof:"auth"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageSpec) Reset() {
	*x = ImageSpec{}
	mi := &file_proto_container_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSpec) ProtoMessage() {}

func (x *ImageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSpec.ProtoReflect.Descriptor instead.
func (*ImageSpec) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ImageSpec) GetRegistry() string {
	if x != nil && x.Registry != nil {
		return *x.Registry
	}
	return ""
}

func (x *ImageSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageSpec) GetAuth() isImageSpec_Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ImageSpec) GetBasicAuth() *BasicAuth {
	if x != nil {
		if x, ok := x.Auth.(*ImageSpec_BasicAuth); ok {
			return x.BasicAuth
		}
	}
	return nil
}

type isImageSpec_Auth interface {
	isImageSpec_Auth()
}

type ImageSpec_BasicAuth struct {
	BasicAuth *BasicAuth `protobuf:"bytes,3,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}

func (*ImageSpec_BasicAuth) isImageSpec_Auth() {}

// Basic authentication for private registries
type BasicAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicAuth) Reset() {
	*x = BasicAuth{}
	mi := &file_proto_container_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicAuth) ProtoMessage() {}

func (x *BasicAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicAuth.ProtoReflect.Descriptor instead.
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{8}
}

func (x *BasicAuth) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BasicAuth) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU limit (e.g., "1.0" for 1 CPU)
	CpuLimit *string `protobuf:"bytes,1,opt,name=cpu_limit,json=cpuLimit,proto3,oneof" json:"cpu_limit,omitempty"`
	// Memory limit (e.g., "512m", "1g")
	MemoryLimit   *string `protobuf:"bytes,2,opt,name=memory_limit,json=memoryLimit,proto3,oneof" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_proto_container_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{9}
}

func (x *ResourceLimits) GetCpuLimit() string {
	if x != nil && x.CpuLimit != nil {
		return *x.CpuLimit
	}
	return ""
}

func (x *ResourceLimits) GetMemoryLimit() string {
	if x != nil && x.MemoryLimit != nil {
		return *x.MemoryLimit
	}
	return ""
}

type NetworkConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Network policy rules
	Rules []*NetworkRule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	// Default policy (allow/deny)
	DefaultPolicy *string `protobuf:"bytes,2,opt,name=default_policy,json=defaultPolicy,proto3,oneof" json:"default_policy,omitempty"`
	// Custom DNS servers
	DnsServers    []string `protobuf:"bytes,3,rep,name=dns_servers,json=dnsServers,proto3" json:"dns_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_proto_container_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkConfig) GetRules() []*NetworkRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkConfig) GetDefaultPolicy() string {
	if x != nil && x.DefaultPolicy != nil {
		return *x.DefaultPolicy
	}
	return ""
}

func (x *NetworkConfig) GetDnsServers() []string {
	if x != nil {
		return x.DnsServers
	}
	return nil
}

type NetworkRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rule type (allow/deny)
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// Protocol (tcp/udp/icmp)
	Protocol *string `protobuf:"bytes,2,opt,name=protocol,proto3,oneof" json:"protocol,omitempty"`
	// Destination CIDR
	Destination *string `protobuf:"bytes,3,opt,name=destination,proto3,oneof" json:"destination,omitempty"`
	// Port range start (inclusive)
	PortRangeStart *uint32 `protobuf:"varint,4,opt,name=port_range_start,json=portRangeStart,proto3,oneof" json:"port_range_start,omitempty"`
	// Port range end (inclusive)
	PortRangeEnd  *uint32 `protobuf:"varint,5,opt,name=port_range_end,json=portRangeEnd,proto3,oneof" json:"port_range_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRule) Reset() {
	*x = NetworkRule{}
	mi := &file_proto_container_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRule) ProtoMessage() {}

func (x *NetworkRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRule.ProtoReflect.Descriptor instead.
func (*NetworkRule) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *NetworkRule) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *NetworkRule) GetDestination() string {
	if x != nil && x.Destination != nil {
		return *x.Destination
	}
	return ""
}

func (x *NetworkRule) GetPortRangeStart() uint32 {
	if x != nil && x.PortRangeStart != nil {
		return *x.PortRangeStart
	}
	return 0
}

func (x *NetworkRule) GetPortRangeEnd() uint32 {
	if x != nil && x.PortRangeEnd != nil {
		return *x.PortRangeEnd
	}
	return 0
}

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by state (running, exited, all)
	Filter        *string `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{12}
}

func (x *ListContainersRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerInfo       `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{13}
}

func (x *ListContainersResponse) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	State         ContainerState         `protobuf:"varint,3,opt,name=state,proto3,enum=container_manager.ContainerState" json:"state,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt    *string                `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	ExitCode      *int32                 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Command       []string               `protobuf:"bytes,7,rep,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_proto_container_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerInfo) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CREATED
}

func (x *ContainerInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContainerInfo) GetFinishedAt() string {
	if x != nil && x.FinishedAt != nil {
		return *x.FinishedAt
	}
	return ""
}

func (x *ContainerInfo) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ContainerInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

type GetContainerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusRequest) Reset() {
	*x = GetContainerStatusRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusRequest) ProtoMessage() {}

func (x *GetContainerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusRequest.ProtoReflect.Descriptor instead.
func (*GetContainerStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{15}
}

func (x *GetContainerStatusRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type GetContainerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Status        *ContainerStatus       `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerStatusResponse) Reset() {
	*x = GetContainerStatusResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerStatusResponse) ProtoMessage() {}

func (x *GetContainerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerStatusResponse.ProtoReflect.Descriptor instead.
func (*GetContainerStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{16}
}

func (x *GetContainerStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetContainerStatusResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetContainerStatusResponse) GetStatus() *ContainerStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ContainerStatus struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	State       ContainerState         `protobuf:"varint,2,opt,name=state,proto3,enum=container_manager.ContainerState" json:"state,omitempty"`
	CreatedAt   string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt   *string                `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	FinishedAt  *string                `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	ExitCode    *int32                 `protobuf:"varint,6,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Pid         *int32                 `protobuf:"varint,7,opt,name=pid,proto3,oneof" json:"pid,omitempty"`
	Config      *ContainerConfig       `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	// I/O statistics
	IoStats *IOStats `protobuf:"bytes,9,opt,name=io_stats,json=ioStats,proto3" json:"io_stats,omitempty"`
	// Unix timestamp when container should be cleaned up (if cleanup enabled)
	CleanupAfter  *int64 `protobuf:"varint,10,opt,name=cleanup_after,json=cleanupAfter,proto3,oneof" json:"cleanup_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_proto_container_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{17}
}

func (x *ContainerStatus) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerStatus) GetState() ContainerState {
	if x != nil {
		return x.State
	}
	return ContainerState_CREATED
}

func (x *ContainerStatus) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContainerStatus) GetStartedAt() string {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return ""
}

func (x *ContainerStatus) GetFinishedAt() string {
	if x != nil && x.FinishedAt != nil {
		return *x.FinishedAt
	}
	return ""
}

func (x *ContainerStatus) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ContainerStatus) GetPid() int32 {
	if x != nil && x.Pid != nil {
		return *x.Pid
	}
	return 0
}

func (x *ContainerStatus) GetConfig() *ContainerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ContainerStatus) GetIoStats() *IOStats {
	if x != nil {
		return x.IoStats
	}
	return nil
}

func (x *ContainerStatus) GetCleanupAfter() int64 {
	if x != nil && x.CleanupAfter != nil {
		return *x.CleanupAfter
	}
	return 0
}

type IOStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StdinBytes    uint64                 `protobuf:"varint,1,opt,name=stdin_bytes,json=stdinBytes,proto3" json:"stdin_bytes,omitempty"`
	StdoutBytes   uint64                 `protobuf:"varint,2,opt,name=stdout_bytes,json=stdoutBytes,proto3" json:"stdout_bytes,omitempty"`
	StderrBytes   uint64                 `protobuf:"varint,3,opt,name=stderr_bytes,json=stderrBytes,proto3" json:"stderr_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IOStats) Reset() {
	*x = IOStats{}
	mi := &file_proto_container_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IOStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IOStats) ProtoMessage() {}

func (x *IOStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IOStats.ProtoReflect.Descriptor instead.
func (*IOStats) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{18}
}

func (x *IOStats) GetStdinBytes() uint64 {
	if x != nil {
		return x.StdinBytes
	}
	return 0
}

func (x *IOStats) GetStdoutBytes() uint64 {
	if x != nil {
		return x.StdoutBytes
	}
	return 0
}

func (x *IOStats) GetStderrBytes() uint64 {
	if x != nil {
		return x.StderrBytes
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{19}
}

type HealthResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Healthy             bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version             string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RunningContainers   uint32                 `protobuf:"varint,3,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	TotalContainers     uint32                 `protobuf:"varint,4,opt,name=total_containers,json=totalContainers,proto3" json:"total_containers,omitempty"`
	IsolationRunnerPath *string                `protobuf:"bytes,5,opt,name=isolation_runner_path,json=isolationRunnerPath,proto3,oneof" json:"isolation_runner_path,omitempty"`
	HealthIssues        []string               `protobuf:"bytes,6,rep,name=health_issues,json=healthIssues,proto3" json:"health_issues,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{20}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetRunningContainers() uint32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

func (x *HealthResponse) GetTotalContainers() uint32 {
	if x != nil {
		return x.TotalContainers
	}
	return 0
}

func (x *HealthResponse) GetIsolationRunnerPath() string {
	if x != nil && x.IsolationRunnerPath != nil {
		return *x.IsolationRunnerPath
	}
	return ""
}

func (x *HealthResponse) GetHealthIssues() []string {
	if x != nil {
		return x.HealthIssues
	}
	return nil
}

type GetNodeResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResourcesRequest) Reset() {
	*x = GetNodeResourcesRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResourcesRequest) ProtoMessage() {}

func (x *GetNodeResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResourcesRequest.ProtoReflect.Descriptor instead.
func (*GetNodeResourcesRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{21}
}

type GetNodeResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Resources     *NodeResources         `protobuf:"bytes,3,opt,name=resources,proto3,oneof" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResourcesResponse) Reset() {
	*x = GetNodeResourcesResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResourcesResponse) ProtoMessage() {}

func (x *GetNodeResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResourcesResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResourcesResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{22}
}

func (x *GetNodeResourcesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetNodeResourcesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetNodeResourcesResponse) GetResources() *NodeResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

type NodeResources struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CPU
	CpuCores        uint32  `protobuf:"varint,1,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	CpuUsagePercent float32 `protobuf:"fixed32,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	// Memory (bytes)
	MemoryTotalBytes     uint64  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	MemoryAvailableBytes uint64  `protobuf:"varint,4,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	MemoryUsedBytes      uint64  `protobuf:"varint,5,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryUsagePercent   float32 `protobuf:"fixed32,6,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	// Disk (bytes)
	DiskTotalBytes     uint64  `protobuf:"varint,7,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	DiskAvailableBytes uint64  `protobuf:"varint,8,opt,name=disk_available_bytes,json=diskAvailableBytes,proto3" json:"disk_available_bytes,omitempty"`
	DiskUsedBytes      uint64  `protobuf:"varint,9,opt,name=disk_used_bytes,json=diskUsedBytes,proto3" json:"disk_used_bytes,omitempty"`
	DiskUsagePercent   float32 `protobuf:"fixed32,10,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	// Container stats
	RunningContainers uint32 `protobuf:"varint,11,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	TotalContainers   uint32 `protobuf:"varint,12,opt,name=total_containers,json=totalContainers,proto3" json:"total_containers,omitempty"`
	// Load averages
	Load_1Min     float32 `protobuf:"fixed32,13,opt,name=load_1min,json=load1min,proto3" json:"load_1min,omitempty"`
	Load_5Min     float32 `protobuf:"fixed32,14,opt,name=load_5min,json=load5min,proto3" json:"load_5min,omitempty"`
	Load_15Min    float32 `protobuf:"fixed32,15,opt,name=load_15min,json=load15min,proto3" json:"load_15min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResources) Reset() {
	*x = NodeResources{}
	mi := &file_proto_container_manager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResources) ProtoMessage() {}

func (x *NodeResources) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResources.ProtoReflect.Descriptor instead.
func (*NodeResources) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{23}
}

func (x *NodeResources) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *NodeResources) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeResources) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *NodeResources) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *NodeResources) GetMemoryUsedBytes() uint64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeResources) GetMemoryUsagePercent() float32 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *NodeResources) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *NodeResources) GetDiskAvailableBytes() uint64 {
	if x != nil {
		return x.DiskAvailableBytes
	}
	return 0
}

func (x *NodeResources) GetDiskUsedBytes() uint64 {
	if x != nil {
		return x.DiskUsedBytes
	}
	return 0
}

func (x *NodeResources) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *NodeResources) GetRunningContainers() uint32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

func (x *NodeResources) GetTotalContainers() uint32 {
	if x != nil {
		return x.TotalContainers
	}
	return 0
}

func (x *NodeResources) GetLoad_1Min() float32 {
	if x != nil {
		return x.Load_1Min
	}
	return 0
}

func (x *NodeResources) GetLoad_5Min() float32 {
	if x != nil {
		return x.Load_5Min
	}
	return 0
}

func (x *NodeResources) GetLoad_15Min() float32 {
	if x != nil {
		return x.Load_15Min
	}
	return 0
}

type GetAvailableImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableImagesRequest) Reset() {
	*x = GetAvailableImagesRequest{}
	mi := &file_proto_container_manager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableImagesRequest) ProtoMessage() {}

func (x *GetAvailableImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableImagesRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableImagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{24}
}

type GetAvailableImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Images        []*ImageInfo           `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableImagesResponse) Reset() {
	*x = GetAvailableImagesResponse{}
	mi := &file_proto_container_manager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableImagesResponse) ProtoMessage() {}

func (x *GetAvailableImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableImagesResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableImagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{25}
}

func (x *GetAvailableImagesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAvailableImagesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *GetAvailableImagesResponse) GetImages() []*ImageInfo {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RepoTags      []string               `protobuf:"bytes,2,rep,name=repo_tags,json=repoTags,proto3" json:"repo_tags,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Created       string                 `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_proto_container_manager_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_container_manager_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_container_manager_proto_rawDescGZIP(), []int{26}
}

func (x *ImageInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageInfo) GetRepoTags() []string {
	if x != nil {
		return x.RepoTags
	}
	return nil
}

func (x *ImageInfo) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ImageInfo) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

var File_proto_container_manager_proto protoreflect.FileDescriptor

const file_proto_container_manager_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/container_manager.proto\x12\x11container_manager\"\xf7\x01\n" +
	"\n" +
	"RunRequest\x12<\n" +
	"\x06create\x18\x01 \x01(\v2\".container_manager.CreateContainerH\x00R\x06create\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12!\n" +
	"\vclose_stdin\x18\x03 \x01(\bH\x00R\n" +
	"closeStdin\x12E\n" +
	"\tterminate\x18\x04 \x01(\v2%.container_manager.TerminateContainerH\x00R\tterminate\x12\x1e\n" +
	"\theartbeat\x18\x05 \x01(\bH\x00R\theartbeatB\t\n" +
	"\arequest\"\x86\x01\n" +
	"\x0fCreateContainer\x12&\n" +
	"\fcontainer_id\x18\x01 \x01(\tH\x00R\vcontainerId\x88\x01\x01\x12:\n" +
	"\x06config\x18\x02 \x01(\v2\".container_manager.ContainerConfigR\x06configB\x0f\n" +
	"\r_container_id\"M\n" +
	"\x12TerminateContainer\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12!\n" +
	"\ftimeout_secs\x18\x02 \x01(\rR\vtimeoutSecs\"\x9a\x02\n" +
	"\vRunResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12?\n" +
	"\acreated\x18\x02 \x01(\v2#.container_manager.ContainerCreatedH\x00R\acreated\x12\x18\n" +
	"\x06stdout\x18\x03 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x04 \x01(\fH\x00R\x06stderr\x126\n" +
	"\x04exit\x18\x05 \x01(\v2 .container_manager.ContainerExitH\x00R\x04exit\x12\x16\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x12\x1a\n" +
	"\amessage\x18\a \x01(\tH\x00R\amessageB\a\n" +
	"\x05event\"n\n" +
	"\x10ContainerCreated\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.container_manager.ContainerStateR\x05state\"J\n" +
	"\rContainerExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\"\xa3\x04\n" +
	"\x0fContainerConfig\x12;\n" +
	"\n" +
	"image_spec\x18\x01 \x01(\v2\x1c.container_manager.ImageSpecR\timageSpec\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x1d\n" +
	"\aworkdir\x18\x03 \x01(\tH\x00R\aworkdir\x88\x01\x01\x12=\n" +
	"\x03env\x18\x04 \x03(\v2+.container_manager.ContainerConfig.EnvEntryR\x03env\x12D\n" +
	"\tresources\x18\x05 \x01(\v2!.container_manager.ResourceLimitsH\x01R\tresources\x88\x01\x01\x12?\n" +
	"\anetwork\x18\x06 \x01(\v2 .container_manager.NetworkConfigH\x02R\anetwork\x88\x01\x01\x12&\n" +
	"\ftimeout_secs\x18\a \x01(\rH\x03R\vtimeoutSecs\x88\x01\x01\x12\x1d\n" +
	"\acleanup\x18\b \x01(\bH\x04R\acleanup\x88\x01\x01\x12\x12\n" +
	"\x04args\x18\t \x03(\tR\x04args\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_workdirB\f\n" +
	"\n" +
	"_resourcesB\n" +
	"\n" +
	"\b_networkB\x0f\n" +
	"\r_timeout_secsB\n" +
	"\n" +
	"\b_cleanup\"\x96\x01\n" +
	"\tImageSpec\x12\x1f\n" +
	"\bregistry\x18\x01 \x01(\tH\x01R\bregistry\x88\x01\x01\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12=\n" +
	"\n" +
	"basic_auth\x18\x03 \x01(\v2\x1c.container_manager.BasicAuthH\x00R\tbasicAuthB\x06\n" +
	"\x04authB\v\n" +
	"\t_registry\"C\n" +
	"\tBasicAuth\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"y\n" +
	"\x0eResourceLimits\x12 \n" +
	"\tcpu_limit\x18\x01 \x01(\tH\x00R\bcpuLimit\x88\x01\x01\x12&\n" +
	"\fmemory_limit\x18\x02 \x01(\tH\x01R\vmemoryLimit\x88\x01\x01B\f\n" +
	"\n" +
	"_cpu_limitB\x0f\n" +
	"\r_memory_limit\"\xa5\x01\n" +
	"\rNetworkConfig\x124\n" +
	"\x05rules\x18\x01 \x03(\v2\x1e.container_manager.NetworkRuleR\x05rules\x12*\n" +
	"\x0edefault_policy\x18\x02 \x01(\tH\x00R\rdefaultPolicy\x88\x01\x01\x12\x1f\n" +
	"\vdns_servers\x18\x03 \x03(\tR\n" +
	"dnsServersB\x11\n" +
	"\x0f_default_policy\"\x8c\x02\n" +
	"\vNetworkRule\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1f\n" +
	"\bprotocol\x18\x02 \x01(\tH\x00R\bprotocol\x88\x01\x01\x12%\n" +
	"\vdestination\x18\x03 \x01(\tH\x01R\vdestination\x88\x01\x01\x12-\n" +
	"\x10port_range_start\x18\x04 \x01(\rH\x02R\x0eportRangeStart\x88\x01\x01\x12)\n" +
	"\x0eport_range_end\x18\x05 \x01(\rH\x03R\fportRangeEnd\x88\x01\x01B\v\n" +
	"\t_protocolB\x0e\n" +
	"\f_destinationB\x13\n" +
	"\x11_port_range_startB\x11\n" +
	"\x0f_port_range_end\"?\n" +
	"\x15ListContainersRequest\x12\x1b\n" +
	"\x06filter\x18\x01 \x01(\tH\x00R\x06filter\x88\x01\x01B\t\n" +
	"\a_filter\"Z\n" +
	"\x16ListContainersResponse\x12@\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2 .container_manager.ContainerInfoR\n" +
	"containers\"\xa0\x02\n" +
	"\rContainerInfo\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x127\n" +
	"\x05state\x18\x03 \x01(\x0e2!.container_manager.ContainerStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12$\n" +
	"\vfinished_at\x18\x05 \x01(\tH\x00R\n" +
	"finishedAt\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x06 \x01(\x05H\x01R\bexitCode\x88\x01\x01\x12\x18\n" +
	"\acommand\x18\a \x03(\tR\acommandB\x0e\n" +
	"\f_finished_atB\f\n" +
	"\n" +
	"_exit_code\">\n" +
	"\x19GetContainerStatusRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xa7\x01\n" +
	"\x1aGetContainerStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12?\n" +
	"\x06status\x18\x03 \x01(\v2\".container_manager.ContainerStatusH\x01R\x06status\x88\x01\x01B\b\n" +
	"\x06_errorB\t\n" +
	"\a_status\"\xf3\x03\n" +
	"\x0fContainerStatus\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.container_manager.ContainerStateR\x05state\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\"\n" +
	"\n" +
	"started_at\x18\x04 \x01(\tH\x00R\tstartedAt\x88\x01\x01\x12$\n" +
	"\vfinished_at\x18\x05 \x01(\tH\x01R\n" +
	"finishedAt\x88\x01\x01\x12 \n" +
	"\texit_code\x18\x06 \x01(\x05H\x02R\bexitCode\x88\x01\x01\x12\x15\n" +
	"\x03pid\x18\a \x01(\x05H\x03R\x03pid\x88\x01\x01\x12:\n" +
	"\x06config\x18\b \x01(\v2\".container_manager.ContainerConfigR\x06config\x125\n" +
	"\bio_stats\x18\t \x01(\v2\x1a.container_manager.IOStatsR\aioStats\x12(\n" +
	"\rcleanup_after\x18\n" +
	" \x01(\x03H\x04R\fcleanupAfter\x88\x01\x01B\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_atB\f\n" +
	"\n" +
	"_exit_codeB\x06\n" +
	"\x04_pidB\x10\n" +
	"\x0e_cleanup_after\"p\n" +
	"\aIOStats\x12\x1f\n" +
	"\vstdin_bytes\x18\x01 \x01(\x04R\n" +
	"stdinBytes\x12!\n" +
	"\fstdout_bytes\x18\x02 \x01(\x04R\vstdoutBytes\x12!\n" +
	"\fstderr_bytes\x18\x03 \x01(\x04R\vstderrBytes\"\x0f\n" +
	"\rHealthRequest\"\x96\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12-\n" +
	"\x12running_containers\x18\x03 \x01(\rR\x11runningContainers\x12)\n" +
	"\x10total_containers\x18\x04 \x01(\rR\x0ftotalContainers\x127\n" +
	"\x15isolation_runner_path\x18\x05 \x01(\tH\x00R\x13isolationRunnerPath\x88\x01\x01\x12#\n" +
	"\rhealth_issues\x18\x06 \x03(\tR\fhealthIssuesB\x18\n" +
	"\x16_isolation_runner_path\"\x19\n" +
	"\x17GetNodeResourcesRequest\"\xac\x01\n" +
	"\x18GetNodeResourcesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12C\n" +
	"\tresources\x18\x03 \x01(\v2 .container_manager.NodeResourcesH\x01R\tresources\x88\x01\x01B\b\n" +
	"\x06_errorB\f\n" +
	"\n" +
	"_resources\"\xff\x04\n" +
	"\rNodeResources\x12\x1b\n" +
	"\tcpu_cores\x18\x01 \x01(\rR\bcpuCores\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x02R\x0fcpuUsagePercent\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x04R\x10memoryTotalBytes\x124\n" +
	"\x16memory_available_bytes\x18\x04 \x01(\x04R\x14memoryAvailableBytes\x12*\n" +
	"\x11memory_used_bytes\x18\x05 \x01(\x04R\x0fmemoryUsedBytes\x120\n" +
	"\x14memory_usage_percent\x18\x06 \x01(\x02R\x12memoryUsagePercent\x12(\n" +
	"\x10disk_total_bytes\x18\a \x01(\x04R\x0ediskTotalBytes\x120\n" +
	"\x14disk_available_bytes\x18\b \x01(\x04R\x12diskAvailableBytes\x12&\n" +
	"\x0fdisk_used_bytes\x18\t \x01(\x04R\rdiskUsedBytes\x12,\n" +
	"\x12disk_usage_percent\x18\n" +
	" \x01(\x02R\x10diskUsagePercent\x12-\n" +
	"\x12running_containers\x18\v \x01(\rR\x11runningContainers\x12)\n" +
	"\x10total_containers\x18\f \x01(\rR\x0ftotalContainers\x12\x1b\n" +
	"\tload_1min\x18\r \x01(\x02R\bload1min\x12\x1b\n" +
	"\tload_5min\x18\x0e \x01(\x02R\bload5min\x12\x1d\n" +
	"\n" +
	"load_15min\x18\x0f \x01(\x02R\tload15min\"\x1b\n" +
	"\x19GetAvailableImagesRequest\"\x91\x01\n" +
	"\x1aGetAvailableImagesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x124\n" +
	"\x06images\x18\x03 \x03(\v2\x1c.container_manager.ImageInfoR\x06imagesB\b\n" +
	"\x06_error\"q\n" +
	"\tImageInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\trepo_tags\x18\x02 \x03(\tR\brepoTags\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x18\n" +
	"\acreated\x18\x04 \x01(\tR\acreated*R\n" +
	"\x0eContainerState\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\n" +
	"\n" +
	"\x06EXITED\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03\x12\x0e\n" +
	"\n" +
	"TERMINATED\x10\x042\xe5\x04\n" +
	"\x10ContainerManager\x12H\n" +
	"\x03Run\x12\x1d.container_manager.RunRequest\x1a\x1e.container_manager.RunResponse(\x010\x01\x12e\n" +
	"\x0eListContainers\x12(.container_manager.ListContainersRequest\x1a).container_manager.ListContainersResponse\x12q\n" +
	"\x12GetContainerStatus\x12,.container_manager.GetContainerStatusRequest\x1a-.container_manager.GetContainerStatusResponse\x12M\n" +
	"\x06Health\x12 .container_manager.HealthRequest\x1a!.container_manager.HealthResponse\x12k\n" +
	"\x10GetNodeResources\x12*.container_manager.GetNodeResourcesRequest\x1a+.container_manager.GetNodeResourcesResponse\x12q\n" +
	"\x12GetAvailableImages\x12,.container_manager.GetAvailableImagesRequest\x1a-.container_manager.GetAvailableImagesResponseBDZBgithub.com/metorial/fleet/holopod/services/container-manager/protob\x06proto3"

var (
	file_proto_container_manager_proto_rawDescOnce sync.Once
	file_proto_container_manager_proto_rawDescData []byte
)

func file_proto_container_manager_proto_rawDescGZIP() []byte {
	file_proto_container_manager_proto_rawDescOnce.Do(func() {
		file_proto_container_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_container_manager_proto_rawDesc), len(file_proto_container_manager_proto_rawDesc)))
	})
	return file_proto_container_manager_proto_rawDescData
}

var file_proto_container_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_container_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_container_manager_proto_goTypes = []any{
	(ContainerState)(0),                // 0: container_manager.ContainerState
	(*RunRequest)(nil),                 // 1: container_manager.RunRequest
	(*CreateContainer)(nil),            // 2: container_manager.CreateContainer
	(*TerminateContainer)(nil),         // 3: container_manager.TerminateContainer
	(*RunResponse)(nil),                // 4: container_manager.RunResponse
	(*ContainerCreated)(nil),           // 5: container_manager.ContainerCreated
	(*ContainerExit)(nil),              // 6: container_manager.ContainerExit
	(*ContainerConfig)(nil),            // 7: container_manager.ContainerConfig
	(*ImageSpec)(nil),                  // 8: container_manager.ImageSpec
	(*BasicAuth)(nil),                  // 9: container_manager.BasicAuth
	(*ResourceLimits)(nil),             // 10: container_manager.ResourceLimits
	(*NetworkConfig)(nil),              // 11: container_manager.NetworkConfig
	(*NetworkRule)(nil),                // 12: container_manager.NetworkRule
	(*ListContainersRequest)(nil),      // 13: container_manager.ListContainersRequest
	(*ListContainersResponse)(nil),     // 14: container_manager.ListContainersResponse
	(*ContainerInfo)(nil),              // 15: container_manager.ContainerInfo
	(*GetContainerStatusRequest)(nil),  // 16: container_manager.GetContainerStatusRequest
	(*GetContainerStatusResponse)(nil), // 17: container_manager.GetContainerStatusResponse
	(*ContainerStatus)(nil),            // 18: container_manager.ContainerStatus
	(*IOStats)(nil),                    // 19: container_manager.IOStats
	(*HealthRequest)(nil),              // 20: container_manager.HealthRequest
	(*HealthResponse)(nil),             // 21: container_manager.HealthResponse
	(*GetNodeResourcesRequest)(nil),    // 22: container_manager.GetNodeResourcesRequest
	(*GetNodeResourcesResponse)(nil),   // 23: container_manager.GetNodeResourcesResponse
	(*NodeResources)(nil),              // 24: container_manager.NodeResources
	(*GetAvailableImagesRequest)(nil),  // 25: container_manager.GetAvailableImagesRequest
	(*GetAvailableImagesResponse)(nil), // 26: container_manager.GetAvailableImagesResponse
	(*ImageInfo)(nil),                  // 27: container_manager.ImageInfo
	nil,                                // 28: container_manager.ContainerConfig.EnvEntry
}
var file_proto_container_manager_proto_depIdxs = []int32{
	2,  // 0: container_manager.RunRequest.create:type_name -> container_manager.CreateContainer
	3,  // 1: container_manager.RunRequest.terminate:type_name -> container_manager.TerminateContainer
	7,  // 2: container_manager.CreateContainer.config:type_name -> container_manager.ContainerConfig
	5,  // 3: container_manager.RunResponse.created:type_name -> container_manager.ContainerCreated
	6,  // 4: container_manager.RunResponse.exit:type_name -> container_manager.ContainerExit
	0,  // 5: container_manager.ContainerCreated.state:type_name -> container_manager.ContainerState
	8,  // 6: container_manager.ContainerConfig.image_spec:type_name -> container_manager.ImageSpec
	28, // 7: container_manager.ContainerConfig.env:type_name -> container_manager.ContainerConfig.EnvEntry
	10, // 8: container_manager.ContainerConfig.resources:type_name -> container_manager.ResourceLimits
	11, // 9: container_manager.ContainerConfig.network:type_name -> container_manager.NetworkConfig
	9,  // 10: container_manager.ImageSpec.basic_auth:type_name -> container_manager.BasicAuth
	12, // 11: container_manager.NetworkConfig.rules:type_name -> container_manager.NetworkRule
	15, // 12: container_manager.ListContainersResponse.containers:type_name -> container_manager.ContainerInfo
	0,  // 13: container_manager.ContainerInfo.state:type_name -> container_manager.ContainerState
	18, // 14: container_manager.GetContainerStatusResponse.status:type_name -> container_manager.ContainerStatus
	0,  // 15: container_manager.ContainerStatus.state:type_name -> container_manager.ContainerState
	7,  // 16: container_manager.ContainerStatus.config:type_name -> container_manager.ContainerConfig
	19, // 17: container_manager.ContainerStatus.io_stats:type_name -> container_manager.IOStats
	24, // 18: container_manager.GetNodeResourcesResponse.resources:type_name -> container_manager.NodeResources
	27, // 19: container_manager.GetAvailableImagesResponse.images:type_name -> container_manager.ImageInfo
	1,  // 20: container_manager.ContainerManager.Run:input_type -> container_manager.RunRequest
	13, // 21: container_manager.ContainerManager.ListContainers:input_type -> container_manager.ListContainersRequest
	16, // 22: container_manager.ContainerManager.GetContainerStatus:input_type -> container_manager.GetContainerStatusRequest
	20, // 23: container_manager.ContainerManager.Health:input_type -> container_manager.HealthRequest
	22, // 24: container_manager.ContainerManager.GetNodeResources:input_type -> container_manager.GetNodeResourcesRequest
	25, // 25: container_manager.ContainerManager.GetAvailableImages:input_type -> container_manager.GetAvailableImagesRequest
	4,  // 26: container_manager.ContainerManager.Run:output_type -> container_manager.RunResponse
	14, // 27: container_manager.ContainerManager.ListContainers:output_type -> container_manager.ListContainersResponse
	17, // 28: container_manager.ContainerManager.GetContainerStatus:output_type -> container_manager.GetContainerStatusResponse
	21, // 29: container_manager.ContainerManager.Health:output_type -> container_manager.HealthResponse
	23, // 30: container_manager.ContainerManager.GetNodeResources:output_type -> container_manager.GetNodeResourcesResponse
	26, // 31: container_manager.ContainerManager.GetAvailableImages:output_type -> container_manager.GetAvailableImagesResponse
	26, // [26:32] is the sub-list for method output_type
	20, // [20:26] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_container_manager_proto_init() }
func file_proto_container_manager_proto_init() {
	if File_proto_container_manager_proto != nil {
		return
	}
	file_proto_container_manager_proto_msgTypes[0].OneofWrappers = []any{
		(*RunRequest_Create)(nil),
		(*RunRequest_Stdin)(nil),
		(*RunRequest_CloseStdin)(nil),
		(*RunRequest_Terminate)(nil),
		(*RunRequest_Heartbeat)(nil),
	}
	file_proto_container_manager_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[3].OneofWrappers = []any{
		(*RunResponse_Created)(nil),
		(*RunResponse_Stdout)(nil),
		(*RunResponse_Stderr)(nil),
		(*RunResponse_Exit)(nil),
		(*RunResponse_Error)(nil),
		(*RunResponse_Message)(nil),
	}
	file_proto_container_manager_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[7].OneofWrappers = []any{
		(*ImageSpec_BasicAuth)(nil),
	}
	file_proto_container_manager_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[17].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[20].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[22].OneofWrappers = []any{}
	file_proto_container_manager_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_container_manager_proto_rawDesc), len(file_proto_container_manager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_container_manager_proto_goTypes,
		DependencyIndexes: file_proto_container_manager_proto_depIdxs,
		EnumInfos:         file_proto_container_manager_proto_enumTypes,
		MessageInfos:      file_proto_container_manager_proto_msgTypes,
	}.Build()
	File_proto_container_manager_proto = out.File
	file_proto_container_manager_proto_goTypes = nil
	file_proto_container_manager_proto_depIdxs = nil
}
